#! /bin/bash
sudo apt update -qy
sudo apt install -qy git nodejs npm zsh neovim

# Symbolically link all dotfiles
~/.dotfiles/install

# If this user's login shell is not already "zsh", attempt to switch.
TEST_CURRENT_SHELL=$(expr "$SHELL" : '.*/\(.*\)')
if [ "$TEST_CURRENT_SHELL" != "zsh" ]; then
    printf "${BLUE}Time to change your default shell to zsh!${NORMAL}\n"
    chsh -s $(grep /zsh$ /etc/shells | tail -1)
    env zsh -l
fi
