#!/usr/bin/bash

FISH_VERSION="fish-3.6.1"

git submodule update --init --recursive

if test ! -d ${FISH_VERSION}; then tar -xf ${FISH_VERSION}.tar.xz; fi
if test ! -f ~/.zshrc_local; then touch ~/.zshrc_local; fi
if test ! -f ~/.bashrc_local; then touch ~/.bashrc_local; fi
if test ! -f ~/.config/fish/config.local.fish; then touch ~/.config/fish/config.local.fish; fi
if test ! -f ~/.config/nvim/lua/init_local.lua; then touch ~/.config/nvim/lua/init_local.lua; fi
if test ! -f proxy_url; then touch proxy_url; echo "proxy_url=" > proxy_url; fi
if test ! -f ~/.gitignore; then git config --global core.excludesFile ~/.gitignore; fi
if test ! -f ~/.tmux/plugins/tpm; then git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm; fi

if ! command -v map &>/dev/null; then
    cd map
    make PREFIX=~/.local install
fi

if ! command -v parallel &>/dev/null; then
    cd gnu_parallel
    ./configure --prefix=$HOME/.local \
        && make \
        && make install
fi

if ! command -v fish &>/dev/null; then
    cd ${FISH_VERSION}
    cmake . \
        && make \
        && sudo make install
fi

if ! command -v nvim &>/dev/null; then
    cd neovim
    git checkout v0.9.1
    make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=$HOME/.local \
        && make install \
        && ln -s $HOME/.local/bin/bin/nvim $HOME/.local/bin
fi
