#!/usr/bin/env bash

# Install package manager - Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Update Homebrew and install packages
brew update
brew tap caskroom/versions
brew install fzf
brew install ctags
brew install ripgrep
brew install fd
brew install vim
brew cask install iterm2

~/.dotfiles/install
